### ISSUE TITLE
question about alarm.com and polling

### ISSUE THREAD

**Issue by smroid** [Xorso/pyalarmdotcom#7]
My understanding is that Home Assistant when using pyalarmdotcom is issuing a query to alarm.com every 30 seconds. My question is: how does alarm.com feel about this usage; might they consider it to be abusive?

Thanks,
-Steve

**Comment by lorddaren** [comment]
I have yet to hear anything from my provider and I have been running it for well over a year. If I remember correctly I try and keep the same session so it would act the same as a page refresh.
